# 集群名
global:
  clusterName: {{clusterName}}
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          # 你们现在不支持 sc,所以注释了
          #storageClassName: standard
          accessModes:
          - {{altermanagerAccesssMode}}
          resources:
            requests:
              storage: {{altermanagerStorage}}
          # 通过 seletor 选择绑定的 pv
          selector:
            matchLabels:
              choerodon.io/name: {{alertmanager-pv}}
grafana:
  adminPassword: "{{adminPassword}}"
  ingress:
    enabled: true
    hosts:
    - {{host}}
    # iframe 嵌套跨域
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Frame-Options: ALLOW-ALL";
  persistence:
    enabled: true
    existingClaim: c7n-grafana-pvc
    accessModes:
    - {{grafanaAccessMode}}
    size: {{grafanaStorage}}
    # 选择 PVC 绑定的 PV
    selector:
      matchLabels:
        choerodon.io/name: {{grafana-pv}}
  grafana.ini:
    auth.generic_oauth:
      name: Choerodon
      enabled: true
      allow_sign_up: true
      client_id: grafana
      client_secret: grafana
      scopes: default
      auth_url: {{api-host}}/oauth/oauth/authorize
      token_url: {{api-host}}/oauth/oauth/token
      api_url: {{api-host}}/base/v1/users/self
    server:
      root_url: http://{{host}}
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - {{prometheusAccessMode}}
          resources:
            requests:
              storage: {{prometheusStorage}}
          # 通过 seletor 选择绑定的 pv
          selector:
            matchLabels:
              choerodon.io/name: {{prometheus-pv}}